//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberResilience.Common.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberResilience.Common.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutUs :.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Compliance Assessment.
        /// </summary>
        public static string AboutUsItem1 {
            get {
                return ResourceManager.GetString("AboutUsItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybersecurity Documents Toolkit.
        /// </summary>
        public static string AboutUsItem2 {
            get {
                return ResourceManager.GetString("AboutUsItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Management Platfrom.
        /// </summary>
        public static string AboutUsItem3 {
            get {
                return ResourceManager.GetString("AboutUsItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer you free and paid public services related to cyber security, discounts for your facilities, and many verification documents and ensure the effectiveness of the tools to work in the facility.
        /// </summary>
        public static string AboutUsParagraph {
            get {
                return ResourceManager.GetString("AboutUsParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        ///                            magna aliqua..
        /// </summary>
        public static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Success Message.
        /// </summary>
        public static string ActionSuccessMessage {
            get {
                return ResourceManager.GetString("ActionSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Base Questions.
        /// </summary>
        public static string AddBaseQuestions {
            get {
                return ResourceManager.GetString("AddBaseQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question Attachments.
        /// </summary>
        public static string AddQuestionAttachments {
            get {
                return ResourceManager.GetString("AddQuestionAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Questions.
        /// </summary>
        public static string AddQuestions {
            get {
                return ResourceManager.GetString("AddQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A108  Baghdad Street, AMMAN , M Y 535022.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Elements.
        /// </summary>
        public static string AddSubElements {
            get {
                return ResourceManager.GetString("AddSubElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template.
        /// </summary>
        public static string AddTemplate {
            get {
                return ResourceManager.GetString("AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template Attachments.
        /// </summary>
        public static string AddTemplateAttachments {
            get {
                return ResourceManager.GetString("AddTemplateAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template Question.
        /// </summary>
        public static string AddTemplateQuestion {
            get {
                return ResourceManager.GetString("AddTemplateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved  ..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Name.
        /// </summary>
        public static string AttachmentName {
            get {
                return ResourceManager.GetString("AttachmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Clause.
        /// </summary>
        public static string BaseClause {
            get {
                return ResourceManager.GetString("BaseClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Question.
        /// </summary>
        public static string BaseQuestion {
            get {
                return ResourceManager.GetString("BaseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Question Name Ar.
        /// </summary>
        public static string BaseQuestionNameAr {
            get {
                return ResourceManager.GetString("BaseQuestionNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Question Name En.
        /// </summary>
        public static string BaseQuestionNameEn {
            get {
                return ResourceManager.GetString("BaseQuestionNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Questions.
        /// </summary>
        public static string BaseQuestions {
            get {
                return ResourceManager.GetString("BaseQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Questions Details.
        /// </summary>
        public static string BaseQuestionsDetails {
            get {
                return ResourceManager.GetString("BaseQuestionsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Questions Subs.
        /// </summary>
        public static string BaseQuestionsSubs {
            get {
                return ResourceManager.GetString("BaseQuestionsSubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Policy Management Platfrom.
        /// </summary>
        public static string BuildPolicyManagementPlatfrom {
            get {
                return ResourceManager.GetString("BuildPolicyManagementPlatfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Questionnaires.
        /// </summary>
        public static string BuildQuestionnaire {
            get {
                return ResourceManager.GetString("BuildQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Questionnaire Questions.
        /// </summary>
        public static string BuildQuestionnaireQuestions {
            get {
                return ResourceManager.GetString("BuildQuestionnaireQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Toolkits.
        /// </summary>
        public static string BuildToolkit {
            get {
                return ResourceManager.GetString("BuildToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Package.
        /// </summary>
        public static string BusinessPackage {
            get {
                return ResourceManager.GetString("BusinessPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium Package .
        /// </summary>
        public static string BusinessPackage2 {
            get {
                return ResourceManager.GetString("BusinessPackage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call To Action.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us and take our services which help you to find the cyber security assessment result for your organization .
        /// </summary>
        public static string CallContent {
            get {
                return ResourceManager.GetString("CallContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call To Action.
        /// </summary>
        public static string CallContentbtn {
            get {
                return ResourceManager.GetString("CallContentbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clause.
        /// </summary>
        public static string Clause {
            get {
                return ResourceManager.GetString("Clause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance Assessment Result.
        /// </summary>
        public static string ComplianceAssessmentResult {
            get {
                return ResourceManager.GetString("ComplianceAssessmentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact the staff at any time.
        /// </summary>
        public static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Questionnaire Failed.
        /// </summary>
        public static string CreateQuestionnaireFailed {
            get {
                return ResourceManager.GetString("CreateQuestionnaireFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Questionnaire Succes.
        /// </summary>
        public static string CreateQuestionnaireSucces {
            get {
                return ResourceManager.GetString("CreateQuestionnaireSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Attachments.
        /// </summary>
        public static string DeleteAttachments {
            get {
                return ResourceManager.GetString("DeleteAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Base Questions.
        /// </summary>
        public static string DeleteBaseQuestions {
            get {
                return ResourceManager.GetString("DeleteBaseQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Questionnaire Failed.
        /// </summary>
        public static string DeleteQuestionnaireFailed {
            get {
                return ResourceManager.GetString("DeleteQuestionnaireFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Questionnaire Succes.
        /// </summary>
        public static string DeleteQuestionnaireSucces {
            get {
                return ResourceManager.GetString("DeleteQuestionnaireSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sub Questions.
        /// </summary>
        public static string DeleteQuestions {
            get {
                return ResourceManager.GetString("DeleteQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Base Questions.
        /// </summary>
        public static string EditBaseQuestions {
            get {
                return ResourceManager.GetString("EditBaseQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sub Questions.
        /// </summary>
        public static string EditQuestions {
            get {
                return ResourceManager.GetString("EditQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        public static string EditTemplate {
            get {
                return ResourceManager.GetString("EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact@example.com.
        /// </summary>
        public static string EmailContent {
            get {
                return ResourceManager.GetString("EmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        public static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Form.
        /// </summary>
        public static string FileUploadForm {
            get {
                return ResourceManager.GetString("FileUploadForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services 1.
        /// </summary>
        public static string Foot1 {
            get {
                return ResourceManager.GetString("Foot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services 1.
        /// </summary>
        public static string Foot2 {
            get {
                return ResourceManager.GetString("Foot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services 1.
        /// </summary>
        public static string Foot3 {
            get {
                return ResourceManager.GetString("Foot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services 1.
        /// </summary>
        public static string Foot4 {
            get {
                return ResourceManager.GetString("Foot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services 1.
        /// </summary>
        public static string Foot5 {
            get {
                return ResourceManager.GetString("Foot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 1.
        /// </summary>
        public static string Free1 {
            get {
                return ResourceManager.GetString("Free1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 1.
        /// </summary>
        public static string Free2 {
            get {
                return ResourceManager.GetString("Free2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 1.
        /// </summary>
        public static string Free3 {
            get {
                return ResourceManager.GetString("Free3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 1.
        /// </summary>
        public static string Free4 {
            get {
                return ResourceManager.GetString("Free4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 1.
        /// </summary>
        public static string Free5 {
            get {
                return ResourceManager.GetString("Free5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Compliance Assessment.
        /// </summary>
        public static string GeneralServiceHead1 {
            get {
                return ResourceManager.GetString("GeneralServiceHead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybersecurity Documents Toolkit.
        /// </summary>
        public static string GeneralServiceHead2 {
            get {
                return ResourceManager.GetString("GeneralServiceHead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Management Platfrom.
        /// </summary>
        public static string GeneralServiceHead3 {
            get {
                return ResourceManager.GetString("GeneralServiceHead3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check within less than 15 minutes the extent to which your company complies with ISO27001 standard, and also how much time you need to achieve full compliance and certification..
        /// </summary>
        public static string GeneralServiceText1 {
            get {
                return ResourceManager.GetString("GeneralServiceText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure you are on the right track with  ISO27001 standard Documents toolkit.
        /// </summary>
        public static string GeneralServiceText2 {
            get {
                return ResourceManager.GetString("GeneralServiceText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplifiy your policy management process
        ///Managing your policies and staying in compliance should be smooth.
        /// </summary>
        public static string GeneralServiceText3 {
            get {
                return ResourceManager.GetString("GeneralServiceText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Error.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Table.
        /// </summary>
        public static string HideTable {
            get {
                return ResourceManager.GetString("HideTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Period Accurate Expected Time.
        /// </summary>
        public static string ImplementationPeriodAccurateExpectedTime {
            get {
                return ResourceManager.GetString("ImplementationPeriodAccurateExpectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Period Time.
        /// </summary>
        public static string ImplementationPeriodTime {
            get {
                return ResourceManager.GetString("ImplementationPeriodTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Mandatory.
        /// </summary>
        public static string IsMandatory {
            get {
                return ResourceManager.GetString("IsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Payment Methods.
        /// </summary>
        public static string ManagePaymentMethods {
            get {
                return ResourceManager.GetString("ManagePaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent. Thank you!.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / month.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Arabic Characters.
        /// </summary>
        public static string OnlyArabicCharacters {
            get {
                return ResourceManager.GetString("OnlyArabicCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only English Characters.
        /// </summary>
        public static string OnlyEnglishCharacters {
            get {
                return ResourceManager.GetString("OnlyEnglishCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oporations.
        /// </summary>
        public static string Oporations {
            get {
                return ResourceManager.GetString("Oporations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string OurAddress {
            get {
                return ResourceManager.GetString("OurAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Newsletter.
        /// </summary>
        public static string OurNewsletter {
            get {
                return ResourceManager.GetString("OurNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe now and follow the latest news and benefit from the latest services for free via your email.
        /// </summary>
        public static string OurNewsletterDetails {
            get {
                return ResourceManager.GetString("OurNewsletterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid1Details1 {
            get {
                return ResourceManager.GetString("Paid1Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid1Details2 {
            get {
                return ResourceManager.GetString("Paid1Details2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid1Details3 {
            get {
                return ResourceManager.GetString("Paid1Details3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid1Details4 {
            get {
                return ResourceManager.GetString("Paid1Details4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid1Details5 {
            get {
                return ResourceManager.GetString("Paid1Details5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid2Details1 {
            get {
                return ResourceManager.GetString("Paid2Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid2Details2 {
            get {
                return ResourceManager.GetString("Paid2Details2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid2Details3 {
            get {
                return ResourceManager.GetString("Paid2Details3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid2Details4 {
            get {
                return ResourceManager.GetString("Paid2Details4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        public static string Paid2Details5 {
            get {
                return ResourceManager.GetString("Paid2Details5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone :.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub Template Type.
        /// </summary>
        public static string PleaseSelectSubTemplateType {
            get {
                return ResourceManager.GetString("PleaseSelectSubTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Template.
        /// </summary>
        public static string PleaseSelectTemplate {
            get {
                return ResourceManager.GetString("PleaseSelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Template Type.
        /// </summary>
        public static string PleaseSelectTemplateType {
            get {
                return ResourceManager.GetString("PleaseSelectTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now benefit from free and paid services that help you in assessing the security level of your organization.
        /// </summary>
        public static string PricingText {
            get {
                return ResourceManager.GetString("PricingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Attachments.
        /// </summary>
        public static string QuestionAttachments {
            get {
                return ResourceManager.GetString("QuestionAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions Ar.
        /// </summary>
        public static string QuestionsAr {
            get {
                return ResourceManager.GetString("QuestionsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Questions Details.
        /// </summary>
        public static string QuestionsDetails {
            get {
                return ResourceManager.GetString("QuestionsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions En.
        /// </summary>
        public static string QuestionsEn {
            get {
                return ResourceManager.GetString("QuestionsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Draft.
        /// </summary>
        public static string SaveAsDraft {
            get {
                return ResourceManager.GetString("SaveAsDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string Selectfile {
            get {
                return ResourceManager.GetString("Selectfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesHead {
            get {
                return ResourceManager.GetString("ServicesHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Compliance Assessment.
        /// </summary>
        public static string SpService1 {
            get {
                return ResourceManager.GetString("SpService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Compliance Assessment - Free.
        /// </summary>
        public static string SpService1hd {
            get {
                return ResourceManager.GetString("SpService1hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybersecurity Documents Toolkit.
        /// </summary>
        public static string SpService2 {
            get {
                return ResourceManager.GetString("SpService2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybersecurity Documents Toolkit.
        /// </summary>
        public static string SpService2hd {
            get {
                return ResourceManager.GetString("SpService2hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Management Platfrom.
        /// </summary>
        public static string SpService3 {
            get {
                return ResourceManager.GetString("SpService3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Management Platfrom.
        /// </summary>
        public static string SpService3hd {
            get {
                return ResourceManager.GetString("SpService3hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO27001 toolkit   -  ISO 22301 toolkit.
        /// </summary>
        public static string SpService4 {
            get {
                return ResourceManager.GetString("SpService4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO27001 toolkit   -  ISO 22301 toolkit.
        /// </summary>
        public static string SpService4hd {
            get {
                return ResourceManager.GetString("SpService4hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMA toolkit.
        /// </summary>
        public static string SpService5 {
            get {
                return ResourceManager.GetString("SpService5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAMA toolkit.
        /// </summary>
        public static string SpService5hd {
            get {
                return ResourceManager.GetString("SpService5hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECC toolkit.
        /// </summary>
        public static string SpService6 {
            get {
                return ResourceManager.GetString("SpService6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECC toolkit.
        /// </summary>
        public static string SpService6hd {
            get {
                return ResourceManager.GetString("SpService6hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Attachments.
        /// </summary>
        public static string TemplateAttachments {
            get {
                return ResourceManager.GetString("TemplateAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name Arabic.
        /// </summary>
        public static string TemplateNameAr {
            get {
                return ResourceManager.GetString("TemplateNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name English.
        /// </summary>
        public static string TemplateNameEn {
            get {
                return ResourceManager.GetString("TemplateNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Sub Type.
        /// </summary>
        public static string TemplateSubType {
            get {
                return ResourceManager.GetString("TemplateSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Type.
        /// </summary>
        public static string TemplateType {
            get {
                return ResourceManager.GetString("TemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Remember me.
        /// </summary>
        public static string TheRememberme {
            get {
                return ResourceManager.GetString("TheRememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Questionnaire Failed.
        /// </summary>
        public static string UpdateQuestionnaireFailed {
            get {
                return ResourceManager.GetString("UpdateQuestionnaireFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Questionnaire Succes.
        /// </summary>
        public static string UpdateQuestionnaireSucces {
            get {
                return ResourceManager.GetString("UpdateQuestionnaireSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Local Account to Login.
        /// </summary>
        public static string UseLocalAccounttoLogin {
            get {
                return ResourceManager.GetString("UseLocalAccounttoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the CYBresilience.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are cyber security team  making websites with Bootstrap.
        /// </summary>
        public static string Who {
            get {
                return ResourceManager.GetString("Who", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Open This Task.
        /// </summary>
        public static string YouAreNotAllowedToOpenThisTask {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToOpenThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
